name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore Dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Install Additional Dependencies
    - name: Install dependencies
      run: |
        dotnet add package Newtonsoft.Json --version 12.0.1
        dotnet add package Dapper --version 2.0.123
        dotnet add package System.Data.SqlClient --version 4.8.5

    # Build the Solution
    - name: Build
      run: dotnet build --no-restore

    # Test the Solution
    - name: Test
      run: dotnet test --no-build --verbosity normal
