name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear
    # Restore Dependencies
    - name: Restore dependencies
      run: dotnet restore koreklarAPI/koreklarAPI.sln

    # Install Additional Dependencies
    - name: Install dependencies
      run: |
        dotnet add koreklarAPI package Newtonsoft.Json --version 12.0.1 
        dotnet add koreklarAPI package Dapper --version 2.0.123 
        dotnet add koreklarAPI package System.Data.SqlClient --version 4.8.5

    # Build the Solution
    - name: Build
      run: dotnet build koreklarAPI/koreklarAPI.sln --no-restore

    # Test the Solution
    - name: Test
      run: dotnet test --no-build --verbosity normal
